main_app/models.py
from main_app import db
from flask_login import UserMixin
from main_app import login_manager
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model,UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, unique=True)
    password = db.Column(db.String)
    workouts = db.relationship('Workout',backref='user')

    def __init__(self,username,password):
        self.username = username
        self.password = generate_password_hash(password)
    def check_password(self,password):
        return check_password_hash(self.password,password)

class Workout(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    exercises = db.relationship('Exercise',backref='workout')
    time = db.Column(db.DateTime,nullable=False,default=datetime.now)
    def __init__(self,user_id):
        self.user_id = user_id

class Exercise(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    workout_id = db.Column(db.Integer, db.ForeignKey('workout.id'), nullable=False)
    exercise_name = db.Column(db.String, nullable=False)
    weight = db.Column(db.Integer, nullable=False)
    reps = db.Column(db.Integer, nullable=False)
    def __init__(self,workout_id,exercise_name,weight,reps):
        self.workout_id = workout_id
        self.exercise_name = exercise_name
        self.weight = weight
        self.reps = reps

    
    

main_app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired
from main_app.models import User
from wtforms import ValidationError


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('SignUp')
    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Your username has been registered already!') 

main_app/workouts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired

class AddExerciseForm(FlaskForm):
    exercise_name = StringField('Name', validators=[DataRequired()])
    weight = IntegerField('Weight',validators=[DataRequired()])
    reps = IntegerField('Reps', validators=[DataRequired()])
    submit = SubmitField('Add Exercise')

main_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
import os

app = Flask(__name__)

app.config['SECRET_KEY'] = os.urandom(24)

basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://username:password@localhost:5432/mydatabase'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "user.login"

from main_app.core.views import core
from main_app.user.views import user
from main_app.workouts.views import workouts
app.register_blueprint(core)
app.register_blueprint(user)
app.register_blueprint(workouts)

main_app/core/views.py
from flask import render_template,request,Blueprint
from main_app.models import Workout
from flask_login import current_user

core = Blueprint('core',__name__)

@core.route('/')
def index():
    welcome_text = 'SignUp or Login to begin tracking your workouts'
    if current_user.is_authenticated:
        welcome_text = 'Click on "new Workout" to begin working out'
    return render_template('index.html',welcome_text=welcome_text)

main_app/user/views.py
from flask import render_template,request,Blueprint,redirect,url_for,abort
from main_app.user.forms import LoginForm, RegistrationForm
from main_app.models import User, Workout, Exercise
from main_app import db
from flask_login import login_required, current_user, login_user, logout_user



user = Blueprint('user',__name__)

@user.route('/signup',methods=['GET','POST'])
def signup():
    if current_user.is_anonymous:
        form = RegistrationForm()
        if form.validate_on_submit():
            user = User(username=form.username.data,password=form.password.data)
            db.session.add(user)
            db.session.commit()
            login_user(user)
            return redirect(url_for('core.index'))
        return render_template('signup.html',form=form)
    else:
        abort(404)

@user.route('/login',methods=['GET','POST'])
def login():
    if current_user.is_anonymous:
        form = LoginForm()
        if form.validate_on_submit():
            user = User.query.filter_by(username=form.username.data).first()
            if user:
                if user.check_password(form.password.data):
                    login_user(user)
                    return redirect(url_for('core.index'))
        return render_template('login.html',form=form,errors=form.errors.items())
    else:
        abort(404)

@user.route('/history')
@login_required
def history():
    page = request.args.get('page',1,type=int)
    workouts = Workout.query.filter_by(user_id=current_user.id).order_by(Workout.time.desc()).paginate(page=page,per_page=5)
    work_exc = {}
    for i in workouts.items:
        ex_str = ''
        ex_list = []
        for j in i.exercises:
            if j.exercise_name not in ex_list:
                ex_str += str(j.exercise_name + ", ")
                ex_list.append(j.exercise_name)
        work_exc[i] = ex_str.rstrip().rstrip(',')
    return render_template('history.html',work_exc=work_exc,workouts=workouts)

@user.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('core.index'))
    

main_app/workouts/views.py
from flask import render_template,request,Blueprint,redirect,url_for,abort,flash
from main_app.workouts.forms import AddExerciseForm
from flask_login import current_user, login_required
from main_app.models import Exercise, Workout
from main_app import db
from flask import url_for


workouts = Blueprint('workouts',__name__)

@workouts.route('/add_workout')
@login_required
def add_workout():
    new_workout = Workout(user_id=current_user.id)
    db.session.add(new_workout)
    db.session.commit()
    return redirect(url_for('workouts.add_exercise'))

@workouts.route('/add_exercise',methods=['GET','POST'])
@login_required
def add_exercise():
    form = AddExerciseForm()
    if form.validate_on_submit():
        current_workout = Workout.query.filter_by(user_id=current_user.id)[-1]
        exercises = Exercise.query.filter_by(workout_id=current_workout.id)
        new_exercise = Exercise(workout_id=current_workout.id,
                     exercise_name=form.exercise_name.data,
                     weight=form.weight.data,
                     reps=form.reps.data)
        db.session.add(new_exercise)
        db.session.commit()
        return render_template('add_exercise.html', form=form, exercises=exercises[::-1])
    return render_template('add_exercise.html', form=form, exercises=None)

@workouts.route('/workout/int:<workout_id>')
@login_required
def workout(workout_id):
    workout = Workout.query.filter_by(id=workout_id).first()
    return render_template('workout.html',workout=workout)

@workouts.route('/delete/int:<workout_id>',methods=['POST'])
@login_required 
def delete_workout(workout_id):
    workout = Workout.query.filter_by(id=workout_id).first()
    if workout.user_id!=current_user.id:
        abort(403)
    exercises = workout.exercises
    for i in exercises:
        db.session.delete(i)
        db.session.commit()
    db.session.delete(workout)
    db.session.commit()
    flash('Post has been deleted')
    return redirect(url_for('user.history')) 

main_app/templates/add_exercise.html
{% extends 'base.html' %}
{% block content %}
    <br>
    <br>
    <div class="container">
        <div class="jumbotron" align='center'>
            <form method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.exercise_name(class="form-control-sm",placeholder="Exercise Name") }}
                </div>
                <div class="form-group">
                    {{ form.reps(class="form-control-sm", placeholder="Reps") }}
                </div>
                <div class="form-group">
                    {{ form.weight(class="form-control-sm", placeholder="weight") }}
                </div>
                    {{ form.submit(class="btn btn-primary") }}
            </form>
        </div>
    </div>
    <br>
    
    {% if exercises %}
        <div class="container" align='center'>
            <ul class="list-group">
            {% for exercise in exercises %}
                <li class="list-group-item">
                    <div class="row">
                        <div class='col-sm'>{{ exercise.exercise_name }}</div>
                        <div class='col-sm'>Reps: {{ exercise.reps }}</div>
                        <div class='col-sm'>Weight: {{ exercise.weight }}</div>
                    </div>
                </li>
            {% endfor %}
            </ul>
        </div>  
    {% endif %}
    
{% endblock %}

main_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <title>Workout Tracker</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" >
        <div class="container">
        <a class="navbar-brand" href="{{ url_for('core.index') }}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if not current_user.is_authenticated  %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.signup') }}">SignUp</a>
                    </li>
                    
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.history') }}">history</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('workouts.add_workout') }}">New Workout</a>
                    </li>

                {% endif %}
            </ul>
        </div>
        </div>
      </nav>
      
      {% block content %}
      {% endblock %}
</body>
</html>

main_app/templates/history.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1 align="center" >This is your workout history {{ current_user.username }}</h1>
            <br>
        </div>
    </div>
    {% for workout,exercises in work_exc.items() %}
        <div class="container">
            <div class="jumbotron">
                <h2 class="display-4">Date:{{ workout.time.strftime('%d-%m-%Y') }}</h2>
                <h2 class="display-4">Time:{{ workout.time.strftime("%H:%M:%S") }}</h2>
                <hr class="my-4">
                <p>Exercises: {{ exercises }}</p>
                <a class="btn btn-primary btn-lg" href="{{ url_for('workouts.workout', workout_id=workout.id) }}" role="button">View Details</a>
                <form action="{{ url_for('workouts.delete_workout', workout_id=workout.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>            
            </div>
        </div>
    {% endfor %}
    <div class="container" align="center">
        {% for page_num in workouts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
            {% if page_num %}
                {% if workouts.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('user.history',page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('user.history',page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}

main_app/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">WELCOME {% if current_user.is_authenticated %}{{ current_user.username }}{% endif %}</h1>
        <p class="lead">This is a simple Workout tracker</p>
        <hr class="my-4">
        <p>{{ welcome_text }}</p>
    </div>
{% endblock %}

main_app/templates/login.html
{% extends 'base.html' %}
{% block content %}
    <br>
    <br>
    <br>
        <div class="container" align="center">
            <div class="jumbotron">
            <h1>Login</h1><br>
                <form method="POST">
                    {{ form.hidden_tag() }}
                    <h3>{{ form.username.label(class="float-left form-control-label") }}</h3> {{ form.username(class="form-control form-control-lg") }} <br>
                    <h3>{{ form.password.label(class="float-left form-control-label") }}</h3> {{ form.password(class="form-control form-control-lg") }} <br>
                    {{ form.submit(class="float-left btn btn-primary") }}
                    <br>
                </form>
            </div>
        </div>
{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% block content %}
    <br>
    <br>
    <br>
        <div class="container" align="center">
            <div class="jumbotron">
            <h1>SignUp</h1><br>
                <form method="POST">
                    {{ form.hidden_tag() }}
                    <h3>{{ form.username.label(class="float-left form-control-label") }}</h3> {{ form.username(class="form-control form-control-lg") }} <br>
                    <h3>{{ form.password.label(class="float-left form-control-label") }}</h3> {{ form.password(class="form-control form-control-lg") }} <br>
                    {{ form.submit(class="float-left btn btn-primary") }}
                    <br>
                </form>
            </div>
        </div>
{% endblock %}

main_app/templates/workout.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="jumbotron" >
            <h3>The details of the workout you did on {{ workout.time.strftime('%d-%m-%Y') }} at {{ workout.time.strftime("%H:%M:%S") }}</h3>
        </div>
    </div>
    <div class="container">
        <ul class="list-group">
            {% for exercise in workout.exercises[::-1] %}
            <li class="list-group-item">
                <div class="row">
                    <div class='col-sm'>{{ exercise.exercise_name }}</div>
                    <div class='col-sm'>Reps: {{ exercise.reps }}</div>
                    <div class='col-sm'>Weight: {{ exercise.weight }}</div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}